### ISSUE TITLE
Unable to start activity ComponentInfo{com.sophpark.upark/me.ele.amigo.release.ApkReleaseActivity}

### ISSUE THREAD

**Issue by Witype** [eleme/Amigo#105]
`
 Process: com.sophpark.upark:amigo, PID: 13066
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sophpark.upark/me.ele.amigo.release.ApkReleaseActivity}: android.view.InflateException: Binary XML file line #1: Binary XML file line #1: Error inflating class x
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3254)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
                                                       at android.app.ActivityThread.access$1100(ActivityThread.java:222)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:158)
                                                       at android.app.ActivityThread.main(ActivityThread.java:7237)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                    Caused by: android.view.InflateException: Binary XML file line #1: Binary XML file line #1: Error inflating class x
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:551)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
                                                       at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:474)
                                                       at android.app.Activity.setContentView(Activity.java:2387)
                                                       at me.ele.amigo.release.ApkReleaseActivity.onCreate(SourceFile:31)
                                                       at android.app.Activity.performCreate(Activity.java:6876)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350) 
                                                       at android.app.ActivityThread.access$1100(ActivityThread.java:222) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:158) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:7237) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                    Caused by: android.view.InflateException: Binary XML file line #1: Error inflating class x
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
                                                       at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:474) 
                                                       at android.app.Activity.setContentView(Activity.java:2387) 
                                                       at me.ele.amigo.release.ApkReleaseActivity.onCreate(SourceFile:31) 
                                                       at android.app.Activity.performCreate(Activity.java:6876) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350) 
                                                       at android.app.ActivityThread.access$1100(ActivityThread.java:222) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:158) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:7237) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.x" on path: DexPathList[[zip file "/data/app/com.sophpark.upark-1/base.apk"],nativeLibraryDirectories=[/data/app/com.sophpark.upark-1/lib/arm, /data/app/com.sophpark.upark-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:595)
                                                       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:689)
                                                       at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:68)
                                                       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:706)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:774)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:498) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
                                                       at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:474) 
                                                       at android.app.Activity.setContentView(Activity.java:2387) 
                                                       at me.ele.amigo.release.ApkReleaseActivity.onCreate(SourceFile:31) 
                                                       at android.app.Activity.performCreate(Activity.java:6876) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350) 
                                                       at android.app.ActivityThread.access$1100(ActivityThread.java:222) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:158) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:7237) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                   	Suppressed: java.lang.ClassNotFoundException: android.view.x
                                                       at java.lang.Class.classForName(Native Method)
                                                       at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                       at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                       		... 25 more
                                                    Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
`

amigo_layout更新布局

`
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:gravity="center"
    android:background="#ffffff">

    <ImageView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:src="@mipmap/ic_upgrading"
        android:drawablePadding="@dimen/activity_margin_middle"
        android:textColor="@color/secondary_text"
        android:contentDescription="@string/app_name"/>

    <LinearLayout
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:gravity="center_vertical"
        android:layout_marginTop="@dimen/activity_margin_middle"
        android:orientation="horizontal">

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:textColor="@color/secondary_text"
            android:text="请稍后"/>

    </LinearLayout>

</LinearLayout>`

新旧版本apk只是versionCode进行了修改，

**Comment by peacepassion** [comment]
java.lang.ClassNotFoundException: Didn't find class "android.view.x"  

麻烦把完整的layout文件贴出来看一下

**Comment by Witype** [comment]
最下面就是layout文件，

**Comment by Witype** [comment]
代码有混淆，

**Comment by peacepassion** [comment]
奇怪的是，`android.view.*`都被混淆了？

**Comment by Witype** [comment]
我发现是混淆的问题，我关闭混淆就没有任何问题，但是android.view.*下面的混淆是使用SDK提供的规则

**Comment by peacepassion** [comment]
`android.**`不可能混淆的吧。

检查一下`build.gradle`的配置。

**Comment by Witype** [comment]
这和使用support包有没有关系哦，
build.gradle设置

`
 release {
                minifyEnabled true
                shrinkResources true
                signingConfig signingConfigs.release
                proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
               ....
} 
`

**Comment by peacepassion** [comment]
麻烦再把layout文件完整的贴出来一下，上面贴的不太对。

**Comment by Witype** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:gravity="center"
    android:background="#ffffff">

    <ImageView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:src="@mipmap/ic_upgrading"
        android:drawablePadding="@dimen/activity_margin_middle"
        android:textColor="@color/secondary_text"
        android:contentDescription="@string/app_name"/>

    <LinearLayout
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:gravity="center_vertical"
        android:layout_marginTop="@dimen/activity_margin_middle"
        android:orientation="horizontal">

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:textColor="@color/secondary_text"
            android:text="请稍后"/>

    </LinearLayout>

</LinearLayout>`

**Comment by peacepassion** [comment]
这不是一个合法的layout文件

**Comment by Witype** [comment]
不好意思，有点玩不懂md，你在刷新一下看看。

**Comment by peacepassion** [comment]
layout文件看上去没啥问题。  

问题出在为什么系统会去读取`android.view.x`，这个就太奇怪了。   

方便把demo或者apk发出来么？我反编译看下

**Comment by Witype** [comment]
http://pan.baidu.com/s/1eRJErTo
只能分享到百度云了，apk已经混淆。

**Comment by peacepassion** [comment]
![image](https://cloud.githubusercontent.com/assets/5254121/19218574/14e454e8-8e30-11e6-80dc-aeeec8d8562f.png)

![image](https://cloud.githubusercontent.com/assets/5254121/19218571/feeedf1e-8e2f-11e6-8bb9-88951705c771.png)

`AndroidManifest.xml`中配置的layout错了

**Comment by Witype** [comment]
这是为何，这个内容是哪里来的？
![image](https://cloud.githubusercontent.com/assets/6899329/19218579/4f3ea7ce-8e30-11e6-8dea-c98bf9a69431.png)
![image](https://cloud.githubusercontent.com/assets/6899329/19218581/59f212a0-8e30-11e6-96ad-51afdec2c604.png)

**Comment by peacepassion** [comment]
这个是你自己配置的，用作释放patch apk时的前台UI.

**Comment by Witype** [comment]
对啊，但是我指向的是layout中的layout_update布局，而且在android studio中的build文件夹中合并的res文件也是没有问题的。为什么跑打包release就只有<x/>
![image](https://cloud.githubusercontent.com/assets/6899329/19218628/61d383fe-8e31-11e6-9b0c-6bd799458b42.png)

**Comment by peacepassion** [comment]
找到原因了，proguard开了shrinkResources true, 而这个layout没有在代码中被直接引用到，因此被proguard给shrink为x了

**Comment by peacepassion** [comment]
所以，把shrinkResources设为false就好了
