### ISSUE TITLE
调用workLater后重启APP并没有开始修复APP

### ISSUE THREAD

**Issue by Witype** [eleme/Amigo#108]
Log
begin merge file installApkPath:/data/app/com.sophpark.upark-1/base.apk patchApkPath:/data/user/0/com.sophpark.upark/files/amigo/amigo_patch.apk
Amigo Log：
```
10-10 10:01:26.731 13644-13644/? E/Amigo: working checksum: 1585798850
10-10 10:01:27.351 13644-13644/? E/Amigo: load dex process
```
将apk文件下载到：/data/user/0/com.sophpark.upark/files/amigo/amigo_patch.apk
Activity代码中调用如下代码
```
boolean patchWorked = Amigo.hasWorked();
        if (!patchWorked) {
            Amigo.workLater(this, file);
            return;
        }
        int workingPatchVersion = Amigo.workingPatchVersion(getApplication());
        if (workingPatchVersion < CommonUtils.getVersionCode(getApplication(), file)) {
            Amigo.workLater(this, file);
        }
```
在调用Amigo.workLater(this, file);方法后重启App，app并没有修复，如果直接调用Amigo.work(this, patchApkFile);是没有问题的，但是会有几个几秒的黑屏。谢谢！

**Comment by FtheGFW** [comment]
1.  Amigo.workLater(this, file)后需要彻底杀死你的app；
2. Amigo.work(this, patchApkFile)导致的黑屏问题可能是你没有设置loading的theme和layout

**Comment by c1024** [comment]
@FtheGFW 借这个地方问一下,我发现最新版workLater后，设置里面杀死程序，重启不会应用新的补丁。
要等workLater完调用dexOptimization完成，重启才会应用新的补丁。

**Comment by FtheGFW** [comment]
是的，只有dexOpt成功执行后，下次重启才能应用新补丁，主要是dalvik和art实际执行的都是优化后的dex，如果amigo在dexOpt过程中就被干掉了，worklater就等于失败了 @c1024

**Comment by Witype** [comment]
@FtheGFW 我明白了，谢谢！
另外还有个问题
我在launchMode=默认的页面(比较深)调用Amigo.workLater(this, file)在完成更新后会重启App，有时候会返回上一层Activity，
在的launchMode=singleTask的Activty(首页非LAUNCHER)下运行Amigo.workLater(this, file)更新完成后会退出App不会重启，这是为何?

**Comment by c1024** [comment]
@FtheGFW 我在测试中遇到一个奇怪问题。应用补丁后，再安装最新版本，发现会启动ApkReleaseActivity。我因为开启 shrinkResources导致崩溃，才发现。
崩溃日志如下：
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.test:amigo, PID: 25416
                                                                      java.lang.RuntimeException: Unable to start activity ComponentInfo{com.test/me.ele.amigo.release.ApkReleaseActivity}: android.view.InflateException: Binary XML file line #1: Binary XML file line #1: Error inflating class x
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                       Caused by: android.view.InflateException: Binary XML file line #1: Binary XML file line #1: Error inflating class x
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                          at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393)
                                                                          at android.app.Activity.setContentView(Activity.java:2172)
                                                                          at me.ele.amigo.release.ApkReleaseActivity.onCreate(ApkReleaseActivity.java:31)
                                                                          at android.app.Activity.performCreate(Activity.java:6251)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:148) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                       Caused by: android.view.InflateException: Binary XML file line #1: Error inflating class x
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                          at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393) 
                                                                          at android.app.Activity.setContentView(Activity.java:2172) 
                                                                          at me.ele.amigo.release.ApkReleaseActivity.onCreate(ApkReleaseActivity.java:31) 
                                                                          at android.app.Activity.performCreate(Activity.java:6251) 
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:148) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                       Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.x" on path: DexPathList[[zip file "/data/app/com.mocoo.dfwc-1/base.apk"],nativeLibraryDirectories=[/data/app/com.mocoo.dfwc-1/lib/arm, /data/app/com.mocoo.dfwc-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
                                                                          at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                          at android.view.LayoutInflater.createView(LayoutInflater.java:583)
                                                                          at android.view.LayoutInflater.onCreateView(LayoutInflater.java:677)
                                                                          at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:68)
                                                                          at android.view.LayoutInflater.onCreateView(LayoutInflater.java:694)
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:762)
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                          at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393) 
                                                                          at android.app.Activity.setContentView(Activity.java:2172) 
                                                                          at me.ele.amigo.release.ApkReleaseActivity.onCreate(ApkReleaseActivity.java:31) 
                                                                          at android.app.Activity.performCreate(Activity.java:6251) 
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:148) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                      	Suppressed: java.lang.ClassNotFoundException: android.view.x
                                                                          at java.lang.Class.classForName(Native Method)
                                                                          at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                          at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                          		... 25 more
                                                                       Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by peacepassion** [comment]
@c1024 参考 #105

**Comment by c1024** [comment]
@peacepassion 我现在问题是已经是最新版了，Amigo里面却判断存在补丁，导致运行崩溃。从逻辑上说，安装最新版，之前补丁应该清除掉的。这个问题好像在多次应用补丁后会出现。

**Comment by peacepassion** [comment]
@c1024 你安装新版本的时候，有增加version么？

**Comment by c1024** [comment]
@peacepassion 安装的新版本就是最后应用的补丁apk,版本相同

**Comment by peacepassion** [comment]
我们这边的判断逻辑是，如果host升级了version，会清掉patch，否则不清的。你确认一下前后两个host之间的version.

**Comment by c1024** [comment]
@peacepassion 就是说如果应用的patch版本是110，再安装版本110，不清patch。所以应用patch后，只能安装大于补丁版本的apk,不然有问题？

**Comment by peacepassion** [comment]
这样做的话，肯定不会清掉Patch，但有没有问题倒不确定。  
一般情况下，安装新的host肯定会升级version的。
