### ISSUE TITLE
实际在使用Amigo过程中还有许多问题

### ISSUE THREAD

**Issue by Witype** [eleme/Amigo#128]
Amigo:0.4.2
我APP三个版本
1、305
2、 400
2、 401
305版本到400、401代码改动较大，只新增了一个Activity，那么我现在的问题是
305 -> 400 和 305->401使用Amigo.workLater后重启app会停止运行并报错：

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sophpark.upark/com.sophpark.upark.ui.splash.SplashActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
```

400->401 使用同样的方法在三星S6 edge上没有任何问题，在HTC 802w就会出现NoClass找不到Activity的错误。

**Comment by JackCho** [comment]
如果不新增Activity的话，也会出现同样的问题不？

**Comment by Witype** [comment]
400->401只是在Gradle更改了VersionCode，我这边有配合Bspatch，我单独将最后合并的Apk包拿出来安装是没有问题的，把packageName/file/amigo/xxx/patch.apk拿出来安装也米有问题。
另外我有使用混淆。

**Comment by JackCho** [comment]
OK，问题已收到。我们尝试复现下，有进展会在这里同步到你

**Comment by Witype** [comment]
好的，谢谢，我之前在只更新版本号的情况下进行了多版本迭代热修复（1->2->3->4）都没有问题。一下是日志，
~~~
origin path : /data/app/com.sophpark.upark-1/base.apk , diffFile path :/data/user/0/com.sophpark.upark/cache/apk/diff-upark1.8.6.306_origin-upark1.8.6.311_origin.apk , patch path/data/user/0/com.sophpark.upark/cache/amigo/amigo_patch.apk
10-27 11:43:02.241 32117-458/? I/bspatch.c: 开始打包之。。。。。。
10-27 11:43:02.241 32117-458/? I/bspatch.c: bspatch
10-27 11:43:02.241 32117-458/? I/bspatch.c: /data/app/com.sophpark.upark-1/base.apk
10-27 11:43:02.241 32117-458/? I/bspatch.c: /data/user/0/com.sophpark.upark/cache/amigo/amigo_patch.apk
10-27 11:43:02.241 32117-458/? I/bspatch.c: /data/user/0/com.sophpark.upark/cache/apk/diff-upark1.8.6.306_origin-upark1.8.6.311_origin.apk
10-27 11:43:02.241 32117-458/? I/bspatch.c: Point 0
10-27 11:43:02.241 32117-458/? I/bspatch.c: Patch is opened
10-27 11:43:02.241 32117-458/? I/bspatch.c: Point 1
10-27 11:43:02.241 32117-458/? I/bspatch.c: Point 2
10-27 11:43:02.241 32117-458/? I/bspatch.c: Point 3
10-27 11:43:02.241 32117-458/? I/bspatch.c: Point 4
10-27 11:43:02.241 32117-458/? I/bspatch.c: Point 5
10-27 11:43:02.291 32117-458/? I/bspatch.c: Point 6
10-27 11:43:03.061 32117-458/? I/bspatch.c: Point 7
10-27 11:43:03.061 32117-458/? I/bspatch.c: Point 8
10-27 11:43:03.091 32117-458/? I/bspatch.c: Point 9
10-27 11:43:03.091 32117-458/? I/bspatch.c: Point 10
10-27 11:43:03.091 32117-458/? I/bspatch.c: 理论上此处就成功了
.....
10-27 11:43:03.241 461-461/? E/Amigo: working checksum: 
10-27 11:43:03.251 461-461/? W/System.err: java.lang.RuntimeException: Patch apk doesn't exists
10-27 11:43:03.251 461-461/? W/System.err:     at me.ele.amigo.Amigo.onCreate(Unknown Source)
10-27 11:43:03.251 461-461/? W/System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)
10-27 11:43:03.251 461-461/? W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6329)
10-27 11:43:03.251 461-461/? W/System.err:     at android.app.ActivityThread.access$1800(ActivityThread.java:222)
10-27 11:43:03.251 461-461/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1861)
10-27 11:43:03.251 461-461/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-27 11:43:03.251 461-461/? W/System.err:     at android.os.Looper.loop(Looper.java:158)
10-27 11:43:03.251 461-461/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7237)
10-27 11:43:03.251 461-461/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
10-27 11:43:03.251 461-461/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
10-27 11:43:03.251 461-461/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
10-27 11:43:03.311 461-461/? D/InjectionManager: InjectionManager
10-27 11:43:03.311 461-461/? D/InjectionManager: fillFeatureStoreMap com.sophpark.upark
10-27 11:43:03.311 461-461/? I/InjectionManager: Constructor com.sophpark.upark, Feature store :{}
10-27 11:43:03.311 461-461/? I/InjectionManager: featureStore :{}
10-27 11:43:03.311 461-461/? E/ApkReleaser: release doing--->false, checksum: 2059458475
10-27 11:43:03.311 461-483/? W/System.err: mkdir failed: EEXIST (File exists) : /data/user/0/com.sophpark.upark/files/amigo
10-27 11:43:03.311 461-483/? W/System.err: mkdir failed: EEXIST (File exists) : /data/user/0/com.sophpark.upark/code_cache
10-27 11:43:03.311 461-483/? W/System.err: mkdir failed: EEXIST (File exists) : /data/user/0/com.sophpark.upark/files/amigo/2059458475/dexes
10-27 11:43:03.801 461-516/? I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-27 11:43:03.801 461-516/? I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-27 11:43:03.801 3065-3711/? D/EnterpriseController: netId is 0
10-27 11:43:03.801 3065-3711/? D/Netd: getNetworkForDns: using netid 555 for uid 10489
10-27 11:43:04.301 461-483/? D/NativeLibraryHelperCompat: supportedAbis : [armeabi-v7a]
10-27 11:43:04.311 461-483/? D/NativeLibraryHelperCompat: supportedAbis : [armeabi-v7a]
10-27 11:43:04.311 461-483/? E/NativeLibraryHelper: Failed to load assets verifier: 0
10-27 11:43:04.341 4219-4422/? D/NetworkController.MobileSignalController(0/1): onSignalStrengthsChanged signalStrength=SignalStrength: 99 99 -120 -160 -120 -1 -1 22 -98 -12 154 -1 2147483647 0x3000 gsm|lte level=3
10-27 11:43:04.341 4219-4422/? D/NetworkController.MobileSignalController(0/1): getMobileIconGroup(): 13
10-27 11:43:04.341 4219-4422/? D/NetworkController.MobileSignalController(0/1): updateCMCCMobileIconGroup(): 13
10-27 11:43:04.371 461-483/? D/NativeLibraryHelper: Successfully fsync /data/user/0/com.sophpark.upark/files/amigo/2059458475/libs/libtbt3631.so
10-27 11:43:04.391 461-483/? D/NativeLibraryHelper: Successfully fsync /data/user/0/com.sophpark.upark/files/amigo/2059458475/libs/libTYMapSDK.so
10-27 11:43:04.401 461-483/? D/NativeLibraryHelper: Successfully fsync /data/user/0/com.sophpark.upark/files/amigo/2059458475/libs/libzbar.so
10-27 11:43:04.421 461-483/? D/NativeLibraryHelper: Successfully fsync /data/user/0/com.sophpark.upark/files/amigo/2059458475/libs/libmsc.so
10-27 11:43:04.441 461-483/? D/NativeLibraryHelper: Successfully fsync /data/user/0/com.sophpark.upark/files/amigo/2059458475/libs/libTYLocationEngine.so
10-27 11:43:04.461 461-483/? D/NativeLibraryHelper: Successfully fsync /data/user/0/com.sophpark.upark/files/amigo/2059458475/libs/libgdinamapv4sdk752.so
10-27 11:43:04.471 461-483/? D/NativeLibraryHelper: Successfully fsync /data/user/0/com.sophpark.upark/files/amigo/2059458475/libs/libwtbt144.so
10-27 11:43:04.761 461-483/? D/NativeLibraryHelper: Successfully fsync /data/user/0/com.sophpark.upark/files/amigo/2059458475/libs/libruntimecore_java.so
10-27 11:43:04.781 461-483/? D/NativeLibraryHelper: Successfully fsync /data/user/0/com.sophpark.upark/files/amigo/2059458475/libs/libsqlite3.so
10-27 11:43:04.781 461-483/? D/NativeLibraryHelper: Successfully fsync /data/user/0/com.sophpark.upark/files/amigo/2059458475/libs/libgetuiext2.so
10-27 11:43:04.791 461-483/? D/NativeLibraryHelper: Successfully fsync /data/user/0/com.sophpark.upark/files/amigo/2059458475/libs/libPatcher.so
10-27 11:43:04.791 461-483/? D/NativeLibraryHelper: Successfully fsync /data/user/0/com.sophpark.upark/files/amigo/2059458475/libs/libgdinamapv4sdk752ex.so
10-27 11:43:04.791 461-483/? E/ApkReleaser: dexOptimization
10-27 11:43:04.871 524-524/? I/dex2oat: /system/bin/dex2oat --compiler-filter=speed --dex-file=/data/user/0/com.sophpark.upark/files/amigo/2059458475/dexes/classes.dex --oat-file=/data/user/0/com.sophpark.upark/code_cache/2059458475/amigo-dexes/classes.dex
~~~
应用WorkLater后重启APP
amigo log
~~~
10-27 11:47:05.631 5851-5851/? E/Amigo: working checksum: 2059458475
10-27 11:47:06.701 5851-5851/? E/Amigo: patchApkChecksum-->2059458475, sp record checksum--->2059458475
10-27 11:47:06.711 5851-5851/? E/Amigo: opt dexFile-->/data/user/0/com.sophpark.upark/code_cache/2059458475/amigo-dexes/classes.dex
10-27 11:47:06.711 5851-5851/? E/Amigo: savedChecksum-->3419053129, checksum--->3419053129
10-27 11:47:06.751 5851-5851/? E/Amigo: oldInstrumentation--->android.app.Instrumentation@720be0c
10-27 11:47:06.751 5851-5851/? E/Amigo: setApkInstrumentation success classloader-->dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.sophpark.upark-1/base.apk"],nativeLibraryDirectories=[/data/app/com.sophpark.upark-1/lib/arm, /data/app/com.sophpark.upark-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]]
10-27 11:47:06.751 5851-5851/? E/Amigo: hook handler success
10-27 11:47:06.761 5851-5851/? E/Amigo: clear old patches
10-27 11:47:07.001 5851-5851/? E/AmigoCallback: handleLaunchActivity targetIntent==null
~~~

crash log
~~~
10-27 11:47:07.051 5851-5851/? W/PackageManager: Failure retrieving text 0x7f08002c in package com.sophpark.upark
                                                 android.content.res.Resources$NotFoundException: String resource ID #0x7f08002c
                                                     at android.content.res.Resources.getText(Resources.java:1468)
                                                     at android.app.ApplicationPackageManager.getText(ApplicationPackageManager.java:1898)
                                                     at android.content.pm.ComponentInfo.loadLabel(ComponentInfo.java:141)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3123)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
                                                     at android.app.ActivityThread.access$1100(ActivityThread.java:222)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:158)
                                                     at android.app.ActivityThread.main(ActivityThread.java:7237)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

10-27 11:47:07.931 5851-5851/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.sophpark.upark, PID: 5851
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sophpark.upark/com.sophpark.upark.ui.splash.SplashActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3254)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
                                                     at android.app.ActivityThread.access$1100(ActivityThread.java:222)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:158)
                                                     at android.app.ActivityThread.main(ActivityThread.java:7237)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                  Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                     at android.support.v7.app.i.x(Unknown Source)
                                                     at android.support.v7.app.i.w(Unknown Source)
                                                     at android.support.v7.app.i.b(Unknown Source)
                                                     at android.support.v7.app.a.setContentView(Unknown Source)
                                                     at com.sophpark.upark.ui.common.a.setContentView(Unknown Source)
                                                     at com.sophpark.upark.ui.splash.SplashActivity.onCreate(Unknown Source)
                                                     at android.app.Activity.performCreate(Activity.java:6876)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
                                                     at me.ele.amigo.AmigoInstrumentation.callActivityOnCreate(Unknown Source)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350) 
                                                     at android.app.ActivityThread.access$1100(ActivityThread.java:222) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:158) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:7237) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
10-27 11:47:07.931 3481-4248/? W/ActivityManager:   Force finishing activity com.sophpark.upark/.ui.splash.SplashActivity
~~~

**Comment by JackCho** [comment]
@Witype 我手边只有一台 HTC OneX 4.2.2的机器，我测试了demo，没有发现和你相似的问题。

麻烦你再详细描述下你手机的ROM信息，同时建议你拉下最新的Amigo源码，在你的HTC机器上跑跑demo，看看能不能成功加载新增的activity

**Comment by JackCho** [comment]
This shall be fixed in version [0.5.0](https://github.com/eleme/Amigo/blob/master/CHANGELOG.md#version-050), please try again
