### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by pandavickey** [eleme/Amigo#135]
hello，i used bspatch. when i patched an wrong apk,it crashed!

FATAL EXCEPTION: main
                                                             Process: me.ele.rocket, PID: 5043
                                                             java.lang.NullPointerException: Attempt to read from field 'java.lang.String[] android.content.pm.PackageInfo.requestedPermissions' on a null object reference
                                                                 at me.ele.amigo.utils.PermissionChecker.checkPatchPermission(PermissionChecker.java:23)
                                                                 at me.ele.amigo.Amigo.checkPatchApk(Amigo.java:411)
                                                                 at me.ele.amigo.Amigo.workLater(Amigo.java:373)
                                                                 at me.ele.rocket.util.AppUtil$3$1.run(AppUtil.java:351)
                                                                 at android.os.Handler.handleCallback(Handler.java:815)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                 at android.os.Looper.loop(Looper.java:210)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5809)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)

**Comment by peacepassion** [comment]
@pandavickey 你合成一个错误的apk，也就是说，合出来的其实并不是一个合法的apk?

**Comment by pandavickey** [comment]
对的，amigo给一个非法的apk在check的时候抛异常了

**Comment by peacepassion** [comment]
每次work一个apk的时候，我们都会对apk做个检查，如果这个apk在某些方面不合法，我们都会抛出一个RuntimeException。可以快速定位问题。需要的话，调用方自己可以catch一下work方法。
