### ISSUE TITLE
handleLaunchActivity FAIL

### ISSUE THREAD

**Issue by wznshuai** [eleme/Amigo#153]
1、出现这个npe是什么造成的？

`E/AmigoCallback: handleLaunchActivity FAIL
    java.lang.NullPointerException
        at me.ele.amigo.utils.component.ActivityFinder.getNewLauncherComponent(ActivityFinder.java:67)
        at me.ele.amigo.AmigoCallback.handleLaunchActivity(AmigoCallback.java:72)
        at me.ele.amigo.AmigoCallback.handleMessage(AmigoCallback.java:34)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4745)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
        at dalvik.system.NativeStart.main(Native Method)`

2、能不能在使用workLater这个修复方式时 修复完成那块 发一个LocalBroadcast这样的广播通知一下
`private Handler handler = new Handler() {
        @Override
        public void handleMessage(Message msg) {
            super.handleMessage(msg);
            switch (msg.what) {
                case WHAT_DEX_OPT_DONE:
                    isReleasing = false;
                    String checksum = (String) msg.obj;
                    doneDexOpt(checksum);
                    saveDexAndSoChecksum(checksum);
                    context.getSharedPreferences(SP_NAME, Context.MODE_MULTI_PROCESS)
                            .edit()
                            .putString(Amigo.WORKING_PATCH_APK_CHECKSUM, checksum)
                            .commit();
                    handler.sendEmptyMessageDelayed(WHAT_FINISH, DELAY_FINISH_TIME);
                    break;
                case WHAT_FINISH:
                    System.exit(0);
                    Process.killProcess(Process.myPid());
                    break;
                default:
                    break;
            }
        }
    };`

**Comment by FtheGFW** [comment]
1、这个是由于没有找到你的补丁apk中的launcher activity，请贴一下你的手机型号，api版本等信息
2、可以的

**Comment by wznshuai** [comment]
1、1的问题不能复现了

2、加一个广播以后我们可以自定义一些修复完成的操作，很关键

3、有新的问题
11-17 08:09:31.273 24020-24020/? W/PackageParser: Unable to read AndroidManifest.xml of /mnt/sdcard/xxx/xxx/patch.apk
                                                  java.io.FileNotFoundException: AndroidManifest.xml
                                                      at android.content.res.AssetManager.openXmlAssetNative(Native Method)
                                                      at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:487)
                                                      at android.content.res.AssetManager.openXmlResourceParser(AssetManager.java:455)
                                                      at android.content.pm.PackageParser.parsePackage(PackageParser.java:498)
                                                      at android.content.pm.PackageManager.getPackageArchiveInfo(PackageManager.java:2170)
                                                      at me.ele.amigo.utils.PermissionChecker.checkPatchPermission(PermissionChecker.java:27)
                                                      at me.ele.amigo.PatchChecker.checkPatchApk(PatchChecker.java:58)
                                                      at me.ele.amigo.PatchChecker.checkPatchAndCopy(PatchChecker.java:37)
                                                      at me.ele.amigo.Amigo.workLater(Amigo.java:358)
                                                      at com.xxx.util.hotfix.HotFixUtil.fix(HotFixUtil.java:33)
                                                      at com.xxx.activity.main.MainActivity.firstInit(MainActivity.java:209)
                                                      at com.xxx.activity.main.MainActivity.onCreate(MainActivity.java:148)
                                                      at android.app.Activity.performCreate(Activity.java:5008)
                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
                                                      at android.app.ActivityThread.access$600(ActivityThread.java:130)
                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
                                                      at android.os.Handler.dispatchMessage(Handler.java:99)
                                                      at android.os.Looper.loop(Looper.java:137)
                                                      at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                      at java.lang.reflect.Method.invoke(Method.java:511)
                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                      at dalvik.system.NativeStart.main(Native Method)
11-17 08:09:31.285 24020-24020/? W/System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx/com.xxx.activity.main.MainActivity}: me.ele.amigo.exceptions.IllegalPatchApkException
11-17 08:09:31.285 24020-24020/? W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2059)
11-17 08:09:31.285 24020-24020/? W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
11-17 08:09:31.285 24020-24020/? W/System.err:     at android.app.ActivityThread.access$600(ActivityThread.java:130)
11-17 08:09:31.285 24020-24020/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
11-17 08:09:31.285 24020-24020/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
11-17 08:09:31.285 24020-24020/? W/System.err:     at android.os.Looper.loop(Looper.java:137)
11-17 08:09:31.285 24020-24020/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:4745)
11-17 08:09:31.285 24020-24020/? W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
11-17 08:09:31.285 24020-24020/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:511)
11-17 08:09:31.285 24020-24020/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
11-17 08:09:31.285 24020-24020/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
11-17 08:09:31.285 24020-24020/? W/System.err:     at dalvik.system.NativeStart.main(Native Method)
11-17 08:09:31.285 24020-24020/? W/System.err: Caused by: me.ele.amigo.exceptions.IllegalPatchApkException
11-17 08:09:31.285 24020-24020/? W/System.err:     at me.ele.amigo.utils.PermissionChecker.checkPatchPermission(PermissionChecker.java:30)
11-17 08:09:31.285 24020-24020/? W/System.err:     at me.ele.amigo.PatchChecker.checkPatchApk(PatchChecker.java:58)
11-17 08:09:31.285 24020-24020/? W/System.err:     at me.ele.amigo.PatchChecker.checkPatchAndCopy(PatchChecker.java:37)
11-17 08:09:31.285 24020-24020/? W/System.err:     at me.ele.amigo.Amigo.workLater(Amigo.java:358)
11-17 08:09:31.285 24020-24020/? W/System.err:     at com.xxx.util.hotfix.HotFixUtil.fix(HotFixUtil.java:33)
11-17 08:09:31.285 24020-24020/? W/System.err:     at com.xxx.activity.main.MainActivity.firstInit(MainActivity.java:209)
11-17 08:09:31.285 24020-24020/? W/System.err:     at com.xxx.activity.main.MainActivity.onCreate(MainActivity.java:148)
11-17 08:09:31.285 24020-24020/? W/System.err:     at android.app.Activity.performCreate(Activity.java:5008)
11-17 08:09:31.285 24020-24020/? W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
11-17 08:09:31.285 24020-24020/? W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
11-17 08:09:31.285 24020-24020/? W/System.err: 	... 11 more

各种原因生成了一个错误的patch.apk，后面就造成了主APP的crash, 解决这个问题是要我们用Amigo的时候整个流程也放到一个进程中吗?包括调用workerLater等?

**Comment by FtheGFW** [comment]
首先Amigo默认输入给它的补丁apk是一个正确的补丁apk（即能够被成功安装的apk），所以得你自己去校验补丁apk的完整性，Amigo只会校验补丁包的签名是不是合法，权限是否增加；
然后不需要再新开一个进程去调用amigo的work** api

**Comment by wznshuai** [comment]
amigo 会强制要求关闭instant run?

**Comment by FtheGFW** [comment]
暂时还不支持 @wznshuai

**Comment by wznshuai** [comment]
![image](https://cloud.githubusercontent.com/assets/1897647/20588902/a5971eb6-b253-11e6-818a-87c48364fb0c.png)
加载apply plugin: 'me.ele.amigo'后就会出现上图的情况，正常那些标题是该居中的，但是加载plugin以后就居中失效了...上面的实现用的https://github.com/rey5137/material里的TabPageIndicator 请看看到底是啥情况？是替换application出的问题吗   @FtheGFW

**Comment by JackCho** [comment]
instant-run的问题已经解决，在开发阶段可以选择不启用Amigo 

```groovy
//if you don't want use amigo in dev
amigo {
    disable true //default false
}
```

**Comment by FtheGFW** [comment]
@wznshuai 我这边没有重现你上面的TabPageIndicator的问题，方便的话把你的代码提交一个pr，我checkout下来再试试

**Comment by wznshuai** [comment]
先暂时改用别的实现了  有时间在check下这个问题 然后再打开  谢谢以上的回答 谢谢
