### ISSUE TITLE
版本列表中错误的版本设置，导致app启动时产生IllegalPatchApkException错误并崩溃

### ISSUE THREAD

**Issue by 320749903** [eleme/Amigo#176]
设置好差分补丁后，app的基础版本又改动后，出现这种情况

**Comment by JackCho** [comment]
请把日志贴一下

**Comment by twiceyuan** [comment]
也遇到了相同的问题，错误日志如下：
```
12-19 22:08:15.867 10292-10688/com.twiceyuan.elemepatchdemo V/MD5: Calculated digest: fb150bcdbd7dfce0db1946f5a8ebdb09
12-19 22:08:15.868 10292-10688/com.twiceyuan.elemepatchdemo V/MD5: Provided digest: fb150bcdbd7dfce0db1946f5a8ebdb09
12-19 22:08:21.740 10292-10688/com.twiceyuan.elemepatchdemo W/zipro: Error opening archive /data/user/0/com.twiceyuan.elemepatchdemo/files/amigo-sdk/amigo_patch_fb150bcdbd7dfce0db1946f5a8ebdb09.apk: Invalid file
12-19 22:08:21.740 10292-10688/com.twiceyuan.elemepatchdemo D/asset: failed to open Zip archive '/data/user/0/com.twiceyuan.elemepatchdemo/files/amigo-sdk/amigo_patch_fb150bcdbd7dfce0db1946f5a8ebdb09.apk'
12-19 22:08:21.765 10292-10688/com.twiceyuan.elemepatchdemo E/AndroidRuntime: FATAL EXCEPTION: AmigoSdk
                                                                              Process: com.twiceyuan.elemepatchdemo, PID: 10292
                                                                              me.ele.amigo.exceptions.IllegalPatchApkException
                                                                                  at me.ele.amigo.utils.PermissionChecker.checkPatchPermission(PermissionChecker.java:30)
                                                                                  at me.ele.amigo.PatchChecker.checkPatchApk(PatchChecker.java:46)
                                                                                  at me.ele.amigo.PatchChecker.checkPatchAndCopy(PatchChecker.java:25)
                                                                                  at me.ele.amigo.Amigo.work(Amigo.java:394)
                                                                                  at me.ele.amigo.Amigo.work(Amigo.java:386)
                                                                                  at me.ele.amigo.sdk.AmigoSdk.applyPatchApk(AmigoSdk.java:220)
                                                                                  at me.ele.amigo.sdk.AmigoSdk.access$800(AmigoSdk.java:33)
                                                                                  at me.ele.amigo.sdk.AmigoSdk$2.onSucc(AmigoSdk.java:132)
                                                                                  at me.ele.amigo.sdk.http.Http$1$3.run(Http.java:132)
                                                                                  at android.os.Handler.handleCallback(Handler.java:751)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                                  at android.os.HandlerThread.run(HandlerThread.java:61)
12-19 22:11:26.064 10292-10300/com.twiceyuan.elemepatchdemo W/art: Suspending all threads took: 8.026ms
```

**Comment by wyh497823256** [comment]
02-16 17:01:07.240 13147-13147/com.h.lib.hrecyclerandadapter D/ProviderStub: onCreate
02-16 17:01:07.257 13147-13147/com.h.lib.hrecyclerandadapter E/Amigo: #onCreate working checksum: 1775316115
02-16 17:01:07.290 13147-13147/com.h.lib.hrecyclerandadapter E/me.ele.amigo.PatchChecker: savedChecksum-->1991417783, checksum--->1991417783
02-16 17:01:07.291 13147-13147/com.h.lib.hrecyclerandadapter E/me.ele.amigo.PatchChecker: savedChecksum-->3644747289, checksum--->3644747289
02-16 17:01:07.292 13147-13147/com.h.lib.hrecyclerandadapter E/me.ele.amigo.PatchChecker: savedChecksum-->3014940152, checksum--->3014940152
02-16 17:01:07.294 13147-13147/com.h.lib.hrecyclerandadapter W/System: ClassLoader referenced unknown path: 
02-16 17:01:07.352 13147-13147/com.h.lib.hrecyclerandadapter I/Amigo: hook Resources success
02-16 17:01:07.378 13147-13147/com.h.lib.hrecyclerandadapter D/Amigo: installAndHook: there is no any new activity, skip hooking instrumentation & mH's callback
02-16 17:01:07.432 13147-13147/com.h.lib.hrecyclerandadapter I/IActivityManagerHook: Install ActivityManager Hook 2 old=android.app.ActivityManagerProxy@e7c4b1d,new=android.app.ActivityManagerProxy@e7c4b1d
02-16 17:01:07.433 13147-13147/com.h.lib.hrecyclerandadapter E/IActivityManagerHook: Install ActivityManager 3 Hook  old=android.app.ActivityManagerProxy@e7c4b1d,new=android.app.ActivityManagerProxy@e7c4b1d
02-16 17:01:07.460 13147-13147/com.h.lib.hrecyclerandadapter I/Amigo: installHookFactory success
02-16 17:01:07.469 13147-13147/com.h.lib.hrecyclerandadapter D/HookedMethodHandler: doHookInner beforeInvoke cost 4 ms
02-16 17:01:07.470 13147-13147/com.h.lib.hrecyclerandadapter I/HookedMethodHandler: doHookInner invoke cost 1 ms
02-16 17:01:07.476 13147-13147/com.h.lib.hrecyclerandadapter D/HookedMethodHandler: doHookInner afterInvoke cost 6 ms
02-16 17:01:07.478 13147-13147/com.h.lib.hrecyclerandadapter D/ProxyHook: invoking (public abstract android.content.pm.ApplicationInfo android.content.pm.IPackageManager.getApplicationInfo(java.lang.String,int,int) throws android.os.RemoteException) 
                                                                          cost 11 ms totally
02-16 17:01:07.493 13147-13147/com.h.lib.hrecyclerandadapter D/HookedMethodHandler: doHookInner beforeInvoke cost 1 ms
02-16 17:01:07.495 13147-13147/com.h.lib.hrecyclerandadapter I/HookedMethodHandler: doHookInner invoke cost 2 ms
02-16 17:01:07.503 13147-13147/com.h.lib.hrecyclerandadapter D/HookedMethodHandler: doHookInner afterInvoke cost 8 ms
02-16 17:01:07.504 13147-13147/com.h.lib.hrecyclerandadapter D/ProxyHook: invoking (public abstract android.content.pm.PackageInfo android.content.pm.IPackageManager.getPackageInfo(java.lang.String,int,int) throws android.os.RemoteException) 
                                                                          cost 11 ms totally
02-16 17:01:07.504 13147-13147/com.h.lib.hrecyclerandadapter D/ReceiverFinder: registerNewReceivers: there is no any new receiver
02-16 17:01:07.504 13147-13147/com.h.lib.hrecyclerandadapter I/Amigo: dynamic register new receivers done
02-16 17:01:07.506 13147-13147/com.h.lib.hrecyclerandadapter D/HookedMethodHandler: doHookInner beforeInvoke cost 0 ms
02-16 17:01:07.507 13147-13174/com.h.lib.hrecyclerandadapter W/System: ClassLoader referenced unknown path: /system/framework/tcmclient.jar
02-16 17:01:07.508 13147-13147/com.h.lib.hrecyclerandadapter I/HookedMethodHandler: doHookInner invoke cost 1 ms
02-16 17:01:07.508 13147-13147/com.h.lib.hrecyclerandadapter D/HookedMethodHandler: doHookInner afterInvoke cost 0 ms
02-16 17:01:07.509 13147-13147/com.h.lib.hrecyclerandadapter D/ProxyHook: invoking (public abstract android.content.pm.PackageInfo android.content.pm.IPackageManager.getPackageInfo(java.lang.String,int,int) throws android.os.RemoteException) 
                                                                          cost 2 ms totally
02-16 17:01:07.509 13147-13147/com.h.lib.hrecyclerandadapter D/ContentProviderFinder: installPatchContentProviders: there is no any new provider
02-16 17:01:07.509 13147-13147/com.h.lib.hrecyclerandadapter I/Amigo: installPatchContentProviders done
02-16 17:01:07.510 13147-13147/com.h.lib.hrecyclerandadapter E/amigo_patch_cleaner: clear old patches
02-16 17:01:07.512 13147-13147/com.h.lib.hrecyclerandadapter D/AmigoDirs: deleteAllPatches: 1775316115
02-16 17:01:07.512 13147-13147/com.h.lib.hrecyclerandadapter I/Amigo: installAndHook successfully with patch
02-16 17:01:07.515 13147-13147/com.h.lib.hrecyclerandadapter E/AmigoCallback: handleLaunchActivity targetIntent==null
02-16 17:01:07.558 13147-13147/com.h.lib.hrecyclerandadapter W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
02-16 17:01:07.644 13147-13175/com.h.lib.hrecyclerandadapter D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
02-16 17:01:07.701 13147-13175/com.h.lib.hrecyclerandadapter I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 01/05/16, 5407492, I96a90533a7
02-16 17:01:07.703 13147-13175/com.h.lib.hrecyclerandadapter I/OpenGLRenderer: Initialized EGL, version 1.4
02-16 17:01:38.033 13147-13174/com.h.lib.hrecyclerandadapter V/MD5: Calculated digest: 2352222adb403fad0c6a88e6fd1443ea
02-16 17:01:38.033 13147-13174/com.h.lib.hrecyclerandadapter V/MD5: Provided digest: 2352222adb403fad0c6a88e6fd1443ea
02-16 17:01:38.055 13147-13174/com.h.lib.hrecyclerandadapter D/HookedMethodHandler: doHookInner beforeInvoke cost 2 ms
02-16 17:01:38.057 13147-13174/com.h.lib.hrecyclerandadapter I/HookedMethodHandler: doHookInner invoke cost 2 ms
02-16 17:01:38.057 13147-13174/com.h.lib.hrecyclerandadapter D/HookedMethodHandler: doHookInner afterInvoke cost 0 ms
02-16 17:01:38.073 13147-13174/com.h.lib.hrecyclerandadapter D/ProxyHook: invoking (public abstract android.content.pm.PackageInfo android.content.pm.IPackageManager.getPackageInfo(java.lang.String,int,int) throws android.os.RemoteException) 
                                                                          cost 4 ms totally
                                                                          
                                                                          [ 02-16 17:01:38.087 13147:13174 D/         ]
                                                                          Zip: EOCD not found, /data/user/0/com.h.lib.hrecyclerandadapter/files/amigo-sdk/amigo_patch_2352222adb403fad0c6a88e6fd1443ea.apk is not zip
02-16 17:01:38.087 13147-13174/com.h.lib.hrecyclerandadapter W/zipro: Error opening archive /data/user/0/com.h.lib.hrecyclerandadapter/files/amigo-sdk/amigo_patch_2352222adb403fad0c6a88e6fd1443ea.apk: Invalid file
02-16 17:01:38.087 13147-13174/com.h.lib.hrecyclerandadapter D/asset: failed to open Zip archive '/data/user/0/com.h.lib.hrecyclerandadapter/files/amigo-sdk/amigo_patch_2352222adb403fad0c6a88e6fd1443ea.apk'
02-16 17:01:38.118 13147-13174/com.h.lib.hrecyclerandadapter E/AndroidRuntime: FATAL EXCEPTION: AmigoSdk
                                                                               Process: com.h.lib.hrecyclerandadapter, PID: 13147
                                                                               Theme: themes:{default=overlay:system, iconPack:system, fontPkg:system, com.android.systemui=overlay:system, com.android.systemui.navbar=overlay:com.h2os.youlun}
                                                                               me.ele.amigo.exceptions.IllegalPatchApkException
                                                                                   at me.ele.amigo.utils.PermissionChecker.checkPatchPermission(PermissionChecker.java:30)
                                                                                   at me.ele.amigo.PatchChecker.checkPatchApk(PatchChecker.java:46)
                                                                                   at me.ele.amigo.PatchChecker.checkPatchAndCopy(PatchChecker.java:25)
                                                                                   at me.ele.amigo.Amigo.work(Amigo.java:394)
                                                                                   at me.ele.amigo.Amigo.work(Amigo.java:386)
                                                                                   at me.ele.amigo.sdk.AmigoSdk.applyPatchApk(AmigoSdk.java:220)
                                                                                   at me.ele.amigo.sdk.AmigoSdk.access$800(AmigoSdk.java:33)
                                                                                   at me.ele.amigo.sdk.AmigoSdk$2.onSucc(AmigoSdk.java:132)
                                                                                   at me.ele.amigo.sdk.http.Http$1$3.run(Http.java:132)
                                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                                   at android.os.HandlerThread.run(HandlerThread.java:61)
02-16 17:01:38.273 13147-13153/com.h.lib.hrecyclerandadapter W/art: Suspending all threads took: 17.089ms
02-16 17:01:38.320 13147-13174/com.h.lib.hrecyclerandadapter I/Process: Sending signal. PID: 13147 SIG: 9
@twiceyuan

**Comment by JackCho** [comment]
Amigo-Sdk isn't supported any more
