### ISSUE TITLE
me.ele.amigo.sdk.utils.MD5.calculateMD5

### ISSUE THREAD

**Issue by wsigang** [eleme/Amigo#181]
MD5: Exception while getting FileInputStream
                                                        java.io.FileNotFoundException: /data/data/xxxx/files/amigo-sdk/amigo_patch_775473c49988e26c159eeb186ab9bef7.apk: open failed: ENOENT (No such file or directory)
                                                            at libcore.io.IoBridge.open(IoBridge.java:453)
                                                            at java.io.FileInputStream.<init>(FileInputStream.java:78)
                                                            at me.ele.amigo.sdk.utils.MD5.calculateMD5(MD5.java:47)
                                                            at me.ele.amigo.sdk.utils.MD5.checkMD5(MD5.java:24)
                                                            at me.ele.amigo.sdk.AmigoSdk.verifyPatchFile(AmigoSdk.java:207)
                                                            at me.ele.amigo.sdk.AmigoSdk.access$600(AmigoSdk.java:33)
                                                            at me.ele.amigo.sdk.AmigoSdk$3.onSucc(AmigoSdk.java:163)
                                                            at me.ele.amigo.sdk.http.Http$1$3.run(Http.java:132)
                                                            at android.os.Handler.handleCallback(Handler.java:808)
                                                            at android.os.Handler.dispatchMessage(Handler.java:103)
                                                            at android.os.Looper.loop(Looper.java:193)
                                                            at android.os.HandlerThread.run(HandlerThread.java:61)
                                                         Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
                                                            at libcore.io.Posix.open(Native Method)
                                                            at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
                                                            at libcore.io.IoBridge.open(IoBridge.java:437)
                                                            at java.io.FileInputStream.<init>(FileInputStream.java:78) 
                                                            at me.ele.amigo.sdk.utils.MD5.calculateMD5(MD5.java:47) 
                                                            at me.ele.amigo.sdk.utils.MD5.checkMD5(MD5.java:24) 
                                                            at me.ele.amigo.sdk.AmigoSdk.verifyPatchFile(AmigoSdk.java:207) 
                                                            at me.ele.amigo.sdk.AmigoSdk.access$600(AmigoSdk.java:33) 
                                                            at me.ele.amigo.sdk.AmigoSdk$3.onSucc(AmigoSdk.java:163) 
                                                            at me.ele.amigo.sdk.http.Http$1$3.run(Http.java:132) 
                                                            at android.os.Handler.handleCallback(Handler.java:808) 
                                                            at android.os.Handler.dispatchMessage(Handler.java:103) 
                                                            at android.os.Looper.loop(Looper.java:193) 
                                                            at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by JackCho** [comment]
we will follow this issue ASAP

**Comment by 320749903** [comment]
也出现这种错误，安卓5.0

12-15 16:07:17.520 25739-25759/? E/AmigoSdk: downloaded patch file is wrong
12-15 16:07:19.010 25771-25788/? E/MD5: Exception while getting FileInputStream
                                        java.io.FileNotFoundException: /data/data/com.domain.department.product/files/amigo-sdk/amigo_patch_4de3b92ace0f7dc35630a6d41de738e3.patch: open failed: ENOENT (No such file or directory)
                                            at libcore.io.IoBridge.open(IoBridge.java:456)
                                            at java.io.FileInputStream.<init>(FileInputStream.java:76)
                                            at me.ele.amigo.sdk.utils.MD5.calculateMD5(MD5.java:47)
                                            at me.ele.amigo.sdk.utils.MD5.checkMD5(MD5.java:24)
                                            at me.ele.amigo.sdk.AmigoSdk.verifyPatchFile(AmigoSdk.java:207)
                                            at me.ele.amigo.sdk.AmigoSdk.access$600(AmigoSdk.java:33)
                                            at me.ele.amigo.sdk.AmigoSdk$3.onSucc(AmigoSdk.java:172)
                                            at me.ele.amigo.sdk.http.Http$1$3.run(Http.java:132)
                                            at android.os.Handler.handleCallback(Handler.java:739)
                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                            at android.os.Looper.loop(Looper.java:135)
                                            at android.os.HandlerThread.run(HandlerThread.java:61)
                                         Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
                                            at libcore.io.Posix.open(Native Method)
                                            at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
                                            at libcore.io.IoBridge.open(IoBridge.java:442)
                                            at java.io.FileInputStream.<init>(FileInputStream.java:76) 
                                            at me.ele.amigo.sdk.utils.MD5.calculateMD5(MD5.java:47) 
                                            at me.ele.amigo.sdk.utils.MD5.checkMD5(MD5.java:24) 
                                            at me.ele.amigo.sdk.AmigoSdk.verifyPatchFile(AmigoSdk.java:207) 
                                            at me.ele.amigo.sdk.AmigoSdk.access$600(AmigoSdk.java:33) 
                                            at me.ele.amigo.sdk.AmigoSdk$3.onSucc(AmigoSdk.java:172) 
                                            at me.ele.amigo.sdk.http.Http$1$3.run(Http.java:132) 
                                            at android.os.Handler.handleCallback(Handler.java:739) 
                                            at android.os.Handler.dispatchMessage(Handler.java:95) 
                                            at android.os.Looper.loop(Looper.java:135) 
                                            at android.os.HandlerThread.run(HandlerThread.java:61) 
12-15 16:07:19.011 25771-25788/? E/MD5: calculatedDigest null
12-15 16:07:19.011 25771-25788/? E/AmigoSdk: downloaded patch file is wrong

**Comment by peacepassion** [comment]
@wsgang @320749903 咨询两个问题：
1. 这个问题是必现么？
2. 出现这种情况有什么特征么？比如说网络环境之类的

**Comment by JackCho** [comment]
Amigo-Sdk isn't supported any more
