### ISSUE TITLE
集成不够详细，按照步骤来，报错详情

### ISSUE THREAD

**Issue by wm1993** [eleme/Amigo#193]
java.lang.RuntimeException: Unable to create application me.ele.amigo.Amigo: java.lang.RuntimeException: java.lang.ClassNotFoundException: Didn't find class "me.ele.amigo.acd" on path: /data/app/com.example.testrxjava-13.apk
                                                                                  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4705)
                                                                                  at android.app.ActivityThread.access$1400(ActivityThread.java:168)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1389)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                  at android.os.Looper.loop(Looper.java:177)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5493)
                                                                                  at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:525)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1225)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1041)
                                                                                  at dalvik.system.NativeStart.main(Native Method)

**Comment by JackCho** [comment]
你看下 是不是被你disable了
```groovy

amigo {
    disable false //default false
}

```

又或者你没把 `apply plugin: 'me.ele.amigo'`

**Comment by wm1993** [comment]
现在的问题是：     Process: com.example.testrxjava, PID: 32639
                                                                        java.lang.RuntimeException: Unable to create application me.ele.amigo.Amigo: java.lang.RuntimeException: java.lang.ClassNotFoundException: Didn't find class "me.ele.amigo.acd" on path: DexPathList[[zip file "/data/app/com.example.testrxjava-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.example.testrxjava-1, /vendor/lib, /system/lib]]
                                                                            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4425)
                                                                            at android.app.ActivityThread.access$1500(ActivityThread.java:138)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1259)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:136)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5095)
                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:515)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
                                                                            at dalvik.system.NativeStart.main(Native Method)

**Comment by JackCho** [comment]
执行assemble命令之前，加个clean

`./gradlew clean assembleXXXX`

也可以尝试关闭一下instant-run

**Comment by FtheGFW** [comment]
麻烦你把完整的 gradlew输出的 log 上传一下

**Comment by wm1993** [comment]
Executing tasks: [:testrxjava:assembleDebug]

Parallel execution with configuration on demand is an incubating feature.
amigo plugin version: 0.6.3
Jack is required to support java 8 language features.
Incremental java compilation is an incubating feature.
Jack is required to support java 8 language features.
check instant run
check instant run
:testrxjava:preBuild UP-TO-DATE
:testrxjava:preDebugBuild UP-TO-DATE
:testrxjava:checkDebugManifest
:testrxjava:preReleaseBuild UP-TO-DATE
:testrxjava:prepareComAndroidSupportAnimatedVectorDrawable2421Library
:testrxjava:prepareComAndroidSupportAppcompatV72421Library
:testrxjava:prepareComAndroidSupportCardviewV72421Library
:testrxjava:prepareComAndroidSupportDesign2421Library
:testrxjava:prepareComAndroidSupportMultidex101Library
:testrxjava:prepareComAndroidSupportRecyclerviewV72421Library
:testrxjava:prepareComAndroidSupportSupportCompat2421Library
:testrxjava:prepareComAndroidSupportSupportCoreUi2421Library
:testrxjava:prepareComAndroidSupportSupportCoreUtils2421Library
:testrxjava:prepareComAndroidSupportSupportFragment2421Library
:testrxjava:prepareComAndroidSupportSupportMediaCompat2421Library
:testrxjava:prepareComAndroidSupportSupportV42421Library
:testrxjava:prepareComAndroidSupportSupportVectorDrawable2421Library
:testrxjava:prepareComJakewhartonRxbindingRxbinding030Library
:testrxjava:prepareComJakewhartonRxbindingRxbindingAppcompatV7030Library
:testrxjava:prepareComJakewhartonRxbindingRxbindingDesign030Library
:testrxjava:prepareComTrelloRxlifecycle040Library
:testrxjava:prepareComTrelloRxlifecycleComponents040Library
:testrxjava:prepareIoReactivexRxandroid110Library
:testrxjava:prepareMeEleAmigoLib063Library
:testrxjava:prepareMeEleAmigo_sdk101Library
:testrxjava:prepareMeEleBspatch104Library
:testrxjava:prepareDebugDependencies
:testrxjava:compileDebugAidl
:testrxjava:compileDebugRenderscript
:testrxjava:generateDebugBuildConfig
:testrxjava:mergeDebugShaders
:testrxjava:compileDebugShaders
:testrxjava:generateDebugAssets
:testrxjava:mergeDebugAssets
:testrxjava:generateDebugResValues UP-TO-DATE
:testrxjava:generateDebugResources
:testrxjava:mergeDebugResources
:testrxjava:processDebugManifest
generateCodeTask: generateDebugApplicationInfo execute
:testrxjava:processDebugResources
:testrxjava:generateDebugSources
:testrxjava:incrementalDebugJavaCompilationSafeguard
:testrxjava:compileDebugJavaWithJavac
:testrxjava:compileRetrolambdaDebug
:testrxjava:compileDebugNdk UP-TO-DATE
:testrxjava:compileDebugSources
:testrxjava:prePackageMarkerForDebug
:testrxjava:transformClassesWithDexForDebug
To run dex in process, the Gradle daemon needs a larger heap.
It currently has approximately 910 MB.
For faster builds, increase the maximum heap size for the Gradle daemon to more than 2048 MB.
To do this set org.gradle.jvmargs=-Xmx2048M in the project gradle.properties.
For more information see https://docs.gradle.org/current/userguide/build_environment.html
:testrxjava:mergeDebugJniLibFolders
:testrxjava:transformNative_libsWithMergeJniLibsForDebug
:testrxjava:processDebugJavaRes UP-TO-DATE
:testrxjava:transformResourcesWithMergeJavaResForDebug
:testrxjava:validateDebugSigning
:testrxjava:packageDebug
:testrxjava:zipalignDebug
:testrxjava:assembleDebug

BUILD SUCCESSFUL

Total time: 1 mins 2.706 secs

**Comment by wm1993** [comment]
ample.testrxjava W/PackageParser: Unable to read AndroidManifest.xml of /data/data/com.example.testrxjava/files/amigo-sdk/amigo_patch_e43cbbcebed5a1690a17b39642c34b89.apk
                                                                       java.io.FileNotFoundException: AndroidManifest.xml
                                                                           at android.content.res.AssetManager.openXmlAssetNative(Native Method)
                                                                           at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:488)
                                                                           at android.content.res.AssetManager.openXmlResourceParser(AssetManager.java:456)
                                                                           at android.content.pm.PackageParser.parsePackage(PackageParser.java:528)
                                                                           at android.content.pm.PackageManager.getPackageArchiveInfo(PackageManager.java:2628)
                                                                           at me.ele.amigo.utils.PermissionChecker.checkPatchPermission(PermissionChecker.java:27)
                                                                           at me.ele.amigo.PatchChecker.checkPatchApk(PatchChecker.java:46)
                                                                           at me.ele.amigo.PatchChecker.checkPatchAndCopy(PatchChecker.java:25)
                                                                           at me.ele.amigo.Amigo.work(Amigo.java:394)
                                                                           at me.ele.amigo.Amigo.work(Amigo.java:386)
                                                                           at me.ele.amigo.sdk.AmigoSdk.applyPatchApk(AmigoSdk.java:220)
                                                                           at me.ele.amigo.sdk.AmigoSdk.access$800(AmigoSdk.java:33)
                                                                           at me.ele.amigo.sdk.AmigoSdk$2.onSucc(AmigoSdk.java:132)
                                                                           at me.ele.amigo.sdk.http.Http$1$3.run(Http.java:132)
                                                                           at android.os.Handler.handleCallback(Handler.java:733)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:136)
                                                                           at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by wm1993** [comment]
又出现这个了   擦

**Comment by wm1993** [comment]
D:\youLiaoSvn\android\branch20161012>gradlew
Starting a new Gradle Daemon for this build (subsequent builds will be faster).
Parallel execution is an incubating feature.
Incremental java compilation is an incubating feature.                                         
amigo plugin version: 0.6.3                                                                            
Jack is required to support java 8 language features.                               
Jack is required to support java 8 language features.                                     
check instant run                                                                            
check instant run            
:help                                                                                      
                     
Welcome to Gradle 2.10.
                     
To run a build, run gradlew <task> ...
                     
To see a list of available tasks, run gradlew tasks
                     
To see a list of command-line options, run gradlew --help
                     
To see more detail about a task, run gradlew help --task <task>
                     
BUILD SUCCESSFUL
               
Total time: 19.95 secs

**Comment by FtheGFW** [comment]
这个问题应该是开启 jack & jill 导致的，Amigo还没有做适配，你暂时先把它 disable 掉  @wm1993

**Comment by wm1993** [comment]
jackOptions {
            enabled false
        }  @JackCho

**Comment by wm1993** [comment]
@JackCho         AS默认是开启的？

**Comment by wm1993** [comment]
@JackCho   https://github.com/wm1993/TestAmigo   请指教
