### ISSUE TITLE
Unable to create application me.ele.amigo.Amigo

### ISSUE THREAD

**Issue by wm1993** [eleme/Amigo#196]
java.lang.RuntimeException: Unable to create application me.ele.amigo.Amigo: java.lang.RuntimeException: java.lang.IllegalArgumentException: param apkFile doesn't exist
                                                                            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4425)
                                                                            at android.app.ActivityThread.access$1500(ActivityThread.java:138)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1259)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:136)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5095)
                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:515)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
                                                                            at dalvik.system.NativeStart.main(Native Method)

**Comment by wm1993** [comment]
@JackCho   clean的日志\youLiaoSvn\android\branch20161012>gradle clean                                                                                          
Starting a new Gradle Daemon for this build (subsequent builds will be faster).                                                            
Parallel execution is an incubating feature.                                                                                               
amigo plugin version: 0.6.3                                                                                                                
Jack is required to support java 8 language features.                                                                                      












Parallel execution is an incubating feature.
amigo plugin version: 0.6.3                                                                
Jack is required to support java 8 language features.                              
Incremental java compilation is an incubating feature.
Jack is required to support java 8 language features.                                    
check instant run                                                                           
check instant run           
:clean                      
:testrxjava:clean                 
               
BUILD SUCCESSFUL

**Comment by wm1993** [comment]
@JackCho     {"has_patch":true,"patch":{"version":5,"url":"https://fuss10.elemecdn.com/2/92/d0fba4382ff16b0c10c249d2fa6d7apk.apk","hash":"292d0fba4382ff16b0c10c249d2fa6d7","diff":true,"work":1}}
