### ISSUE TITLE
接入Amigo平台遇到的错误，请大神帮忙

### ISSUE THREAD

**Issue by mengsuwen** [eleme/Amigo#201]
```
2-28 14:52:29.800 7396-7396/me.yifeiyuan.andfixdemo E/Amigo: #onCreate working checksum: 
12-28 14:52:29.800 7396-7396/me.yifeiyuan.andfixdemo D/Amigo: #onCreate Patch apk doesn't exists
12-28 14:52:29.800 7396-7396/me.yifeiyuan.andfixdemo E/amigo_patch_cleaner: clear
12-28 14:52:29.810 7396-7396/me.yifeiyuan.andfixdemo D/AmigoDirs: clear:
12-28 14:52:30.303 7396-7396/me.yifeiyuan.andfixdemo E/dalvikvm: Could not find class 'android.util.ArrayMap', referenced from method me.ele.amigo.PatchResourceLoader.replaceAssetManager
12-28 14:52:30.303 7396-7396/me.yifeiyuan.andfixdemo W/dalvikvm: VFY: unable to resolve check-cast 2114 (Landroid/util/ArrayMap;) in Lme/ele/amigo/PatchResourceLoader;
12-28 14:52:30.303 7396-7396/me.yifeiyuan.andfixdemo D/dalvikvm: VFY: replacing opcode 0x1f at 0x0024

12-28 14:52:30.406 7396-7426/me.yifeiyuan.andfixdemo D/NativeCrypto: doing handshake -- ret=-1
12-28 14:52:30.406 7396-7426/me.yifeiyuan.andfixdemo D/NativeCrypto: ssl=0x5d1b4f28 NativeCrypto_SSL_do_handshake exception => 0
12-28 14:52:30.407 7396-7426/me.yifeiyuan.andfixdemo D/NativeCrypto: ssl=0x5d1b4f28 NativeCrypto_SSL_interrupt
12-28 14:52:30.407 7396-7396/me.yifeiyuan.andfixdemo D/libEGL: loaded /system/lib/egl/libEGL_mali.so
12-28 14:52:30.407 7396-7426/me.yifeiyuan.andfixdemo D/NativeCrypto:  sslNotify, appData=0x5c9be9c8 ret=1
12-28 14:52:30.407 7396-7426/me.yifeiyuan.andfixdemo D/NativeCrypto:  sslNotify, appData=0x5c9be9c8 ret=1
12-28 14:52:30.407 7396-7426/me.yifeiyuan.andfixdemo I/System.out: [CDS]close[40492]
12-28 14:52:30.408 7396-7426/me.yifeiyuan.andfixdemo I/System.out: close [socket][/0.0.0.0:40492]
12-28 14:52:30.408 7396-7426/me.yifeiyuan.andfixdemo W/System.err: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
12-28 14:52:30.408 7396-7396/me.yifeiyuan.andfixdemo D/libEGL: loaded /system/lib/egl/libGLESv1_CM_mali.so
12-28 14:52:30.408 7396-7426/me.yifeiyuan.andfixdemo W/System.err:     at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:381)
12-28 14:52:30.409 7396-7426/me.yifeiyuan.andfixdemo W/System.err:     at libcore.net.http.HttpConnection.setupSecureSocket(HttpConnection.java:209)
12-28 14:52:30.409 7396-7426/me.yifeiyuan.andfixdemo W/System.err:     at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:486)
12-28 14:52:30.409 7396-7426/me.yifeiyuan.andfixdemo W/System.err:     at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:433)
12-28 14:52:30.409 7396-7426/me.yifeiyuan.andfixdemo W/System.err:     at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:290)
12-28 14:52:30.409 7396-7426/me.yifeiyuan.andfixdemo W/System.err:     at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:240)
12-28 14:52:30.409 7396-7426/me.yifeiyuan.andfixdemo W/System.err:     at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:292)
12-28 14:52:30.409 7396-7426/me.yifeiyuan.andfixdemo W/System.err:     at libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:505)
12-28 14:52:30.409 7396-7426/me.yifeiyuan.andfixdemo W/System.err:     at libcore.net.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:134)
12-28 14:52:30.409 7396-7426/me.yifeiyuan.andfixdemo W/System.err:     at me.ele.amigo.sdk.http.Http$1.run(Http.java:97)
12-28 14:52:30.409 7396-7426/me.yifeiyuan.andfixdemo W/System.err:     at android.os.Handler.handleCallback(Handler.java:800)
12-28 14:52:30.409 7396-7426/me.yifeiyuan.andfixdemo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:100)
12-28 14:52:30.409 7396-7426/me.yifeiyuan.andfixdemo W/System.err:     at android.os.Looper.loop(Looper.java:194)
12-28 14:52:30.409 7396-7426/me.yifeiyuan.andfixdemo W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:60)
12-28 14:52:30.410 7396-7426/me.yifeiyuan.andfixdemo W/System.err: Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
12-28 14:52:30.410 7396-7426/me.yifeiyuan.andfixdemo W/System.err:     at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:276)
12-28 14:52:30.410 7396-7426/me.yifeiyuan.andfixdemo W/System.err:     at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:197)
12-28 14:52:30.410 7396-7426/me.yifeiyuan.andfixdemo W/System.err:     at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:585)
12-28 14:52:30.410 7396-7426/me.yifeiyuan.andfixdemo W/System.err:     at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method)
12-28 14:52:30.410 7396-7426/me.yifeiyuan.andfixdemo W/System.err:     at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:378)
12-28 14:52:30.410 7396-7426/me.yifeiyuan.andfixdemo W/System.err: 	... 13 more
12-28 14:52:30.410 7396-7426/me.yifeiyuan.andfixdemo W/System.err: Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
12-28 14:52:30.411 7396-7426/me.yifeiyuan.andfixdemo W/System.err: 	... 18 more
12-28 14:52:30.411 7396-7426/me.yifeiyuan.andfixdemo E/AmigoSdk: request patch info error: code: -1, msg: null, des: null
12-28 14:52:30.411 7396-7396/me.yifeiyuan.andfixdemo D/libEGL: loaded /system/lib/egl/libGLESv2_mali.so
12-28 14:52:30.415 7396-7396/me.yifeiyuan.andfixdemo E/linker: load_library(linker.cpp:761): library "libmaliinstr.so" not found
                                                               
                                                               [ 12-28 14:52:30.417  7396:0x1ce4 E/         ]
                                                               appName=me.yifeiyuan.andfixdemo, acAppName=com.android.cts.openglperf
                                                               
                                                               [ 12-28 14:52:30.417  7396:0x1ce4 E/         ]
                                                               0
                                                               
                                                               [ 12-28 14:52:30.417  7396:0x1ce4 E/         ]
                                                               appName=me.yifeiyuan.andfixdemo, acAppName=com.android.browser
                                                               
                                                               [ 12-28 14:52:30.417  7396:0x1ce4 E/         ]
                                                               0
12-28 14:52:30.419 7396-7396/me.yifeiyuan.andfixdemo D/GraphicBuffer: create handle(0x5c98f048) (w:720, h:1280, f:1)
12-28 14:52:30.420 7396-7396/me.yifeiyuan.andfixdemo D/GraphicBuffer: close handle(0x5c98f048) (w:720 h:1280 f:1)
12-28 14:52:30.421 7396-7396/me.yifeiyuan.andfixdemo D/GraphicBuffer: create handle(0x5c98f048) (w:720, h:1280, f:1)
```

**Comment by peacepassion** [comment]
@mengsuwen 帮忙贴一下系统的信息

**Comment by JackCho** [comment]
Amigo-sdk isn't supported anymore, so close this issue
