### ISSUE TITLE
Database version downgrade error on patch apply

### ISSUE THREAD

**Issue by atulgoswami21** [eleme/Amigo#210]
I have a host which has a db version 7 and i am using greenDao for database.
And then i created a patch file with db version 8 and publish that patch it applies successfully.
And then i created another patch there are some code changes only in this patch no db or any manifest change but when i apply this patch it crashes while applying patch and giving me error 
Fatal Exception: java.lang.RuntimeException: Unable to create application me.ele.amigo.Amigo: java.lang.RuntimeException: android.database.sqlite.SQLiteException: Can't downgrade database from version 8 to 7 while in patch db version is 8.

please take a look and thanks in advance.

`Fatal Exception: java.lang.RuntimeException: Unable to create application me.ele.amigo.Amigo: java.lang.RuntimeException: android.database.sqlite.SQLiteException: Can't downgrade database from version 8 to 7
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5463)
       at android.app.ActivityThread.-wrap2(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1556)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6176)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
Caused by java.lang.RuntimeException: android.database.sqlite.SQLiteException: Can't downgrade database from version 8 to 7
       at me.ele.amigo.Amigo.onCreate(Amigo.java:94)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5460)
       at android.app.ActivityThread.-wrap2(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1556)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6176)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
Caused by android.database.sqlite.SQLiteException: Can't downgrade database from version 8 to 7
       at android.database.sqlite.SQLiteOpenHelper.onDowngrade(SQLiteOpenHelper.java:360)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:254)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
       at com.bizzypulse.bizzypulse.BizzyApplication.setupDatabase(BizzyApplication.java:183)
       at com.bizzypulse.bizzypulse.BizzyApplication.setUpApp(BizzyApplication.java:198)
       at com.bizzypulse.bizzypulse.BizzyApplication.onCreate(BizzyApplication.java:106)
       at me.ele.amigo.Amigo.runOriginalApplication(Amigo.java:310)
       at me.ele.amigo.Amigo.onCreate(Amigo.java:73)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5460)
       at android.app.ActivityThread.-wrap2(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1556)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6176)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)`

>
here is the issue load dex always run host apk which through database downgrade error.
 // ensure load dex process always run host apk not patch apk
            if (ProcessUtils.isLoadDexProcess(this)) {
                Log.e(TAG, "#onCreate load dex process");
                runOriginalApplication();
                return;
            }

**Comment by JackCho** [comment]
It's very dangerous to use like this.`patch` can be removed anytime if you want, and then `Amigo` should run host apk. There isn't too much to do here really for db downgrade.
