### ISSUE TITLE
bsdiff 问题

### ISSUE THREAD

**Issue by songsh** [eleme/Amigo#212]
我用bsdiff 命令生成差分文件，然后更新
Amigo.work(this,downFile);

报错：
Caused by: me.ele.amigo.exceptions.IllegalPatchApkException
                                                                      at me.ele.amigo.utils.PermissionChecker.checkPatchPermission(PermissionChecker.java:30)
                                                                      at me.ele.amigo.PatchChecker.checkPatchApk(PatchChecker.java:46)
                                                                      at me.ele.amigo.PatchChecker.checkPatchAndCopy(PatchChecker.java:25)
                                                                      at me.ele.amigo.Amigo.work(Amigo.java:394)

**Comment by FtheGFW** [comment]
Amigo.work(this,downFile);   
downFile是指 full Apk 文件，而不是差分文件，所以就是说得要你自己在手机上根据差分文件合成出（bug fixed）Apk

**Comment by songsh** [comment]
怎么去合成了，用什么方法？

**Comment by JackCho** [comment]
https://github.com/eleme/bspatch @songsh

**Comment by D-Rusty** [comment]
您好，我这样写也报上面哪个错，谢谢
![image](https://user-images.githubusercontent.com/17473495/30577016-352ff568-9d3e-11e7-9286-f7e29e7bd73d.png)

**Comment by JackCho** [comment]
check whether your `newPath` apk is valid or not
