### ISSUE TITLE
0.6.5 修复后部分手机出现异常了

### ISSUE THREAD

**Issue by qinci** [eleme/Amigo#239]
java.lang.StackOverflowError
 at me.ele.amigo.utils.component.ActivityFinder.getActivityInfoInNewApp(Unknown Source)
 at me.ele.amigo.utils.component.ActivityFinder.getActivityInfoInNewApp(Unknown Source)
 at me.ele.amigo.utils.component.ActivityFinder.getActivityInfoInNewApp(Unknown Source)
  at me.ele.amigo.utils.component.ActivityFinder.getActivityInfoInNewApp(Unknown Source)

**Comment by qinci** [comment]
测试了很多手机 其中一个手机安装后完成后，自动启动时报了这个异常

**Comment by JackCho** [comment]
麻烦把机器型号、ROM版本发下。
AndroidManifest.xml里面有`activity-alias`，有的话，也麻烦贴一下

**Comment by qinci** [comment]
好的，我明天看一下手机，没有配置activity-alias

**Comment by qinci** [comment]
设备机型
OPPO 1107

系统版本
Android 4.4.4,level 19

ROM
Oppo/COLOROS

CPU架构
armeabi-v7a


腾讯云真机地址
http://remote.utest.qq.com/deviceSearch?seqTypeFlag=0&brand=&from=bugly&searchName=1107&utm_source=Bugly&utm_medium=TencentLink&utm_campaign=SingleDevice&utest_channel=318

**Comment by qinci** [comment]
刚用同一个安装包试了一下云真好像没有问题 @JackCho 😂

**Comment by qinci** [comment]
今天  测试机 三星s6 又遇到这个问题了

**Comment by JackCho** [comment]
升下级 `compile 'me.ele:amigo-lib:0.6.7'`
