### ISSUE TITLE
build的时候AmigoPlugin会报NPE错误 version 0.6.6

### ISSUE THREAD

**Issue by wznshuai** [eleme/Amigo#240]
Caused by: java.lang.NullPointerException: Cannot invoke method entries() on null object
	at me.ele.amigo.AmigoPlugin.collectMultiDexInfo(AmigoPlugin.groovy:150)
	at me.ele.amigo.AmigoPlugin$_apply_closure1$_closure5$_closure7$_closure10.doCall(AmigoPlugin.groovy:114)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:596)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:577)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
	... 20 more

**Comment by JackCho** [comment]
应该是你使用的gradle版本的兼容问题，试试gradle 2.14.1

**Comment by qinci** [comment]
我也遇到这个问题了，debug的时候，在部分手机有问题，运行会报Cannot invoke method entries()，release没有问题

**Comment by wznshuai** [comment]
这个错误在任何版本的gradle都会出现呢 下面是一段log打印 无论gradle配置的disable是false 还是 true
amigo {
    disable false //default false
    autoDisableInInstantRunMode true // default false
}
![image](https://user-images.githubusercontent.com/1897647/27822709-2a70ad26-60d9-11e7-958e-a8185980fcfb.png)

**Comment by JackCho** [comment]
@wznshuai 是的

**Comment by wznshuai** [comment]
![image](https://user-images.githubusercontent.com/1897647/27851688-7e3aca8a-618e-11e7-8795-3c1f7df0712b.png)
0.6.7版本这个这个NPE错误是在152行，是对应的master的截图这行吗？什么情况下jarFile会是空的？如何能很好的解决呢？老哥帮帮忙 很关键  gradle plugin不溜啊

**Comment by JackCho** [comment]
`
 classpath 'me.ele:amigo:0.6.8'
`
试试这个，修复了

@wznshuai
