### ISSUE TITLE
隐藏app图标后报错

### ISSUE THREAD

**Issue by anqisx** [eleme/Amigo#248]
07-12 14:26:08.417 8525-8525/? E/dalvikvm: Could not find class 'android.util.ArrayMap', referenced from method me.ele.amigo.PatchResourceLoader.replaceAssetManager
07-12 14:26:08.430 8525-8525/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 java.lang.NullPointerException
                                                     at me.ele.amigo.utils.ProcessUtils.startLauncherIntent(ProcessUtils.java:61)
                                                     at me.ele.amigo.AmigoService.pullUpMainProcess(AmigoService.java:228)
                                                     at me.ele.amigo.AmigoService.handleMsg(AmigoService.java:128)
                                                     at me.ele.amigo.AmigoService.access$000(AmigoService.java:23)
                                                     at me.ele.amigo.AmigoService$3.handleMessage(AmigoService.java:118)
                                                     at android.os.Handler.dispatchMessage(Handler.java:103)
                                                     at android.os.Looper.loop(Looper.java:194)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5463)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:525)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:854)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:621)
                                                     at dalvik.system.NativeStart.main(Native Method)
07-12 14:26:08.441 886-908/? E/AppErrorDialog: Failed to get ILowStorageHandle instance

**Comment by JackCho** [comment]
<img width="777" alt="2017-07-12 5 03 51" src="https://user-images.githubusercontent.com/3806682/28110228-3c6bfd2c-6724-11e7-9327-adfa6cd9f62a.png">
日志信息比较少，看闪退日志应该是launchIntent为null了。

这个是必现么？闪退的机器厂商、ROM版本，尽可能多提供一些信息

**Comment by anqisx** [comment]
项目 主Activity设置<category android:name="android.intent.category.DEFAULT" />后发生的，我现在用0.6.2tag的amigo-lib以module集成，正常的升级都不成功。

**Comment by JackCho** [comment]
请提供尽可能多的信息，没明白你说的东西

**Comment by JackCho** [comment]
no further info to provide here, close this issue temporarily. 
if any info is provided, then I will reopen this.
