### ISSUE TITLE
三星 SM-C7000 android 7.0 手机热更新后crash

### ISSUE THREAD

**Issue by caihuapcl2013** [eleme/Amigo#261]
三星 SM-C7000 android 7.0 手机热更新后crash：
下面是日志（是不是7.0之后手机不支持资源更新，或者说 LayoutInflater.from(context).inflate 这种方式加载资源在7.0上不支持更新）:
    Process: cn.pear.browser, PID: 18951
                                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{cn.pear.browser/cn.pear.browser.activities.SparrowActivity}: android.view.InflateException: Binary XML file line #125: Binary XML file line #125: Error inflating class cn.pear.browser.view.BrowserSearchView
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2984)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
                                                                     at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
                                                                  Caused by: android.view.InflateException: Binary XML file line #125: Binary XML file line #125: Error inflating class cn.pear.browser.view.BrowserSearchView
                                                                  Caused by: android.view.InflateException: Binary XML file line #125: Error inflating class cn.pear.browser.view.BrowserSearchView
                                                                  Caused by: java.lang.reflect.InvocationTargetException
                                                                     at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:652)
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
                                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:525)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:378)
                                                                     at cn.pear.browser.view.x.a(TabView.java:157)
                                                                     at cn.pear.browser.view.x.<init>(TabView.java:148)
                                                                     at cn.pear.browser.view.x.<init>(TabView.java:142)
                                                                     at cn.pear.browser.view.x.<init>(TabView.java:138)
                                                                     at cn.pear.browser.activities.SparrowActivity.c(SparrowActivity.java:400)
                                                                     at cn.pear.browser.activities.SparrowActivity.onCreate(SparrowActivity.java:316)
                                                                     at android.app.Activity.performCreate(Activity.java:6956)
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                                                                     at me.ele.amigo.AmigoInstrumentation.callActivityOnCreate(AmigoInstrumentation.java:320)
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
                                                                     at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
                                                                  Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f040048
                                                                     at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:202)
                                                                     at android.content.res.Resources.loadXmlResourceParser(Resources.java:2970)
                                                                     at android.content.res.Resources.getLayout(Resources.java:1986)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:425)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:378)
                                                                     at cn.pear.browser.view.BrowserSearchView.a(BrowserSearchView.java:184)
                                                                     at cn.pear.browser.view.BrowserSearchView.<init>(BrowserSearchView.java:174)
                                                                     at cn.pear.browser.view.BrowserSearchView.<init>(BrowserSearchView.java:169)
                                                                     at java.lang.reflect.Constructor.newInstance0(Native Method) 
                                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:430) 
                                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:652) 
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794) 
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734) 
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:865) 
                                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:525) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:378) 
                                                                     at cn.pear.browser.view.x.a(TabView.java:157) 
                                                                     at cn.pear.browser.view.x.<init>(TabView.java:148) 
                                                                     at cn.pear.browser.view.x.<init>(TabView.java:142) 
                                                                     at cn.pear.browser.view.x.<init>(TabView.java:138) 
                                                                     at cn.pear.browser.activities.SparrowActivity.c(SparrowActivity.java:400) 
                                                                     at cn.pear.browser.activities.SparrowActivity.onCreate(SparrowActivity.java:316) 
                                                                     at android.app.Activity.performCreate(Activity.java:6956) 
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126) 
                                                                     at me.ele.amigo.AmigoInstrumentation.callActivityOnCreate(AmigoInstrumentation.java:320) 
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927) 
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045) 
                                                                     at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                     at android.os.Looper.loop(Looper.java:154) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6776) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by JackCho** [comment]
支持资源更新的，这个是必现么？
建议剥离一个简易可复现的demo，上传到github一起看

**Comment by caihuapcl2013** [comment]
这是一个必现的BUG ,我们公司所有的7.0手机上都有这种问题！晚点我试着做一相DEMO 看看能不能必现这个问题！

**Comment by caihuapcl2013** [comment]
更新前的布局 layout.xml：
`<?xml` version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:orientation="vertical"
    android:gravity="center"
    android:layout_height="match_parent">

    <Button
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Base APK"
        />

    <Button
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:id="@+id/load_patch"
        android:text="load patch"
        />

</LinearLayout>

要更新的布局 layout.xml 
`<?xml` version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:orientation="vertical"
    android:gravity="center"
    android:layout_height="match_parent">


    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="patch apk"
        />

    <Button
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:id="@+id/load_patch"
        android:visibility="gone"
        android:text="load patch"
        />

</LinearLayout>

MainActivity 代码 ：
`package test.hotfix.hua.com.myapplication;

import android.Manifest;
import android.content.pm.PackageManager;
import android.os.Environment;
import android.support.v4.app.ActivityCompat;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.widget.FrameLayout;

import java.io.File;

import me.ele.amigo.Amigo;

public class MainActivity extends AppCompatActivity {
    private FrameLayout frameLayout;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        frameLayout=(FrameLayout) findViewById(R.id.test_layout);
        View view= LayoutInflater.from(getApplicationContext()).inflate(R.layout.layout,null);
        frameLayout.addView(view);

        view.findViewById(R.id.load_patch).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                updatePath();
            }
        });

        String [] strings={Manifest.permission.WRITE_EXTERNAL_STORAGE};

        ActivityCompat.requestPermissions( MainActivity.this, strings,0);
    }


    protected   void updatePath(){
        File file =new File(Environment.getExternalStorageDirectory(),"test.apk");
        Amigo.workLater(getApplicationContext(), file, new Amigo.WorkLaterCallback() {
            @Override
            public void onPatchApkReleased(boolean b) {
                Log.d("HUA","onPatchApkReleased: "+b);

            }
        });
    }


    public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
        if(grantResults[0]== PackageManager.PERMISSION_GRANTED){
        }

    }
}
`

回调成功，kill app 发现资源没有变化 ！ 这现象只存在于7.0 并且通过 LayoutInflater.from(getApplicationContext()).inflate 方式加载才会出现

**Comment by caihuapcl2013** [comment]
https://github.com/caihuapcl2013/amigoAndrodOBUG 
这个是DEMO项目，打更新包时 只将 layout.xml 改成下面的代码 然后在 三星 SM-C7000 上面运行，结果是并没有出现我想要的 patch apk 字样，如果项目复杂的话会出现 Caused by: android.content.res.Resources$NotFoundException: Resource ID 

```
<?xml` version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:orientation="vertical"
    android:gravity="center"
    android:layout_height="match_parent">


    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="patch apk"
        />

    <Button
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:id="@+id/load_patch"
        android:visibility="gone"
        android:text="load patch"
        />

</LinearLayout>

**Comment by JackCho** [comment]
@caihuapcl2013 我按照你给的代码复现了一圈，还是没能复现。
最好你能提交一个demo repo

**Comment by JackCho** [comment]
@caihuapcl2013 Amigo plugin你没有依赖，同时把android plugin 降到 2.3.0

```groovy
buildscript {
    
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.0'
        classpath 'me.ele:amigo:0.6.8'
    }
}

```

```groovy
apply plugin: 'com.android.application'
apply plugin: 'me.ele.amigo'

```

**Comment by caihuapcl2013** [comment]
@JackCho  不好意思DEMO我忘记加了，加上去可以更新资源，但还是之前的问题在复杂工程里面(有大量代码和资源要更新)必Crash 
现象是更新完了之后，部分新的功能都可以用了（也就是部分资源更新没问题），进入主界面后 CRASH 
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f040048

注：我在想办法做成DEMO, 到时麻烦你看一下
