### ISSUE TITLE
Here is a crash... How to deal?

### ISSUE THREAD

**Issue by yang747046912** [eleme/Amigo#32]
FATAL EXCEPTION: main
                                                                   Process: me.ele.amigo.demo, PID: 21719
                                                                   java.lang.RuntimeException: Unable to create application com.android.tools.fd.runtime.BootstrapApplication: java.lang.IllegalArgumentException: param apkFile cannot be read
                                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4798)
                                                                       at android.app.ActivityThread.access$1600(ActivityThread.java:165)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:150)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
                                                                    Caused by: java.lang.IllegalArgumentException: param apkFile cannot be read
                                                                       at me.ele.amigo.Amigo.work(Amigo.java:419)
                                                                       at me.ele.amigo.demo.ApplicationContext.onCreate(ApplicationContext.java:34)
                                                                       at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:369)
                                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1015)
                                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4786)
                                                                       at android.app.ActivityThread.access$1600(ActivityThread.java:165) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:150) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5546) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

**Comment by JackCho** [comment]
make sure your apk file is readable for app, maybe you pushed apk as root rule

**Comment by captain-miao** [comment]
It happened on Android 6.0.

> java.lang.IllegalArgumentException: param apkFile cannot be read

change targetSdkVersion 22 😰

`    defaultConfig {
        ...
        targetSdkVersion 22
        ...
    }`

**Comment by JackCho** [comment]
yes.
when your `targetSdkVersion` is 23, app needs explicit granted permission from user.

@captain-miao thanks, I submit a PR to fix this

**Comment by JackCho** [comment]
see https://github.com/eleme/Amigo/pull/33/files 

@yang747046912

**Comment by yang747046912** [comment]
@JackCho Thinks!   elme app now is using Amigo!
