### ISSUE TITLE
补丁apk如果资源有变化，使用RemoteViews显示自定义通知有异常

### ISSUE THREAD

**Issue by c1024** [eleme/Amigo#46]
测试中发现，如果补丁apk修改了资源，显示通知使用RemoteViews会有异常。
不同修改，异常不一样。
异常日志如下：

09-09 11:19:45.002 1036-1036/? E/StatusBar: couldn't inflate view for notification com.mocoo.dfwc/0x66
                                            android.view.InflateException: Binary XML file line #21: Error inflating class android.view.View
                                                at android.view.LayoutInflater.createView(LayoutInflater.java:623)
                                                at android.view.LayoutInflater.onCreateView(LayoutInflater.java:655)
                                                at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:66)
                                                at android.view.LayoutInflater.onCreateView(LayoutInflater.java:672)
                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:697)
                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:400)
                                                at android.widget.RemoteViews.apply(RemoteViews.java:2432)
                                                at com.android.systemui.statusbar.BaseStatusBar.inflateViews(BaseStatusBar.java:561)
                                                at com.android.systemui.statusbar.BaseStatusBar.addNotificationViews(BaseStatusBar.java:900)
                                                at com.android.systemui.statusbar.phone.PhoneStatusBar.addNotification(PhoneStatusBar.java:1513)
                                                at com.android.systemui.statusbar.CommandQueue$H.handleMessage(CommandQueue.java:362)
                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                at android.os.Looper.loop(Looper.java:136)
                                                at android.app.ActivityThread.main(ActivityThread.java:5016)
                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                at java.lang.reflect.Method.invoke(Method.java:515)
                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
                                                at dalvik.system.NativeStart.main(Native Method)
                                             Caused by: android.view.InflateException: Binary XML file line #21: Class not allowed to be inflated android.view.View
                                                at android.view.LayoutInflater.failNotAllowed(LayoutInflater.java:637)
                                                at android.view.LayoutInflater.createView(LayoutInflater.java:586)
                                                at android.view.LayoutInflater.onCreateView(LayoutInflater.java:655) 
                                                at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:66) 
                                                at android.view.LayoutInflater.onCreateView(LayoutInflater.java:672) 
                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:697) 
                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:400) 
                                                at android.widget.RemoteViews.apply(RemoteViews.java:2432) 
                                                at com.android.systemui.statusbar.BaseStatusBar.inflateViews(BaseStatusBar.java:561) 
                                                at com.android.systemui.statusbar.BaseStatusBar.addNotificationViews(BaseStatusBar.java:900) 
                                                at com.android.systemui.statusbar.phone.PhoneStatusBar.addNotification(PhoneStatusBar.java:1513) 
                                                at com.android.systemui.statusbar.CommandQueue$H.handleMessage(CommandQueue.java:362) 
                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                at android.os.Looper.loop(Looper.java:136) 
                                                at android.app.ActivityThread.main(ActivityThread.java:5016) 
                                                at java.lang.reflect.Method.invokeNative(Native Method) 
                                                at java.lang.reflect.Method.invoke(Method.java:515) 
                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792) 
                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608) 
                                                at dalvik.system.NativeStart.main(Native Method)

**Comment by c1024** [comment]
不知道是什么错乱了

**Comment by JackCho** [comment]
这个看起来应该不是Amigo的问题，你试着直接运行新的apk看看有没有也出现一样的问题

**Comment by c1024** [comment]
运行新的apk没问题

**Comment by JackCho** [comment]
收到，我们跟踪下这个问题

**Comment by JackCho** [comment]
@c1024 we fixed this issue in https://github.com/eleme/Amigo/pull/58

Notification's show is handled by System server, we may can't do anything more here.
https://github.com/eleme/Amigo/pull/58 is just for hotfix apk's notification show normal, if you want to hotfix a custom layout, you can just fix its view content, not layout itself.

if Amigo is already in your apk, you may need write code like below 
 ```
mBuilder.setSmallIcon(RCompat.getIdentifier(this, R.drawable.ic_ac_grade_lv0));

RemoteViews contentView = new RemoteViews(getPackageName(), RCompat.getIdentifier(this, R.layout.custom_notification));
contentView.setImageViewResource(RCompat.getIdentifier(this, R.id.n_image), RCompat.getIdentifier(this, R.drawable.ic_account_mobile));
contentView.setTextColor(RCompat.getIdentifier(this, R.id.n_text), getResources().getColor(R.color.blue));
```
