### ISSUE TITLE
diff apk don't work, throw exception. diif is binary rather than apk  so that can't certainly read AndroidManifest.xml, i think.... 

### ISSUE THREAD

**Issue by fldroid** [eleme/Amigo#65]
09-18 08:43:40.384 31783-31783/me.ele.demo W/PackageParser: Unable to read AndroidManifest.xml of /storage/emulated/0/demo.apk
                                                            java.io.FileNotFoundException: AndroidManifest.xml
                                                                at android.content.res.AssetManager.openXmlAssetNative(Native Method)
                                                                at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:488)
                                                                at android.content.res.AssetManager.openXmlResourceParser(AssetManager.java:456)
                                                                at android.content.pm.PackageParser.parsePackage(PackageParser.java:528)
                                                                at android.content.pm.PackageManager.getPackageArchiveInfo(PackageManager.java:2629)
                                                                at me.ele.amigo.Amigo.isSignatureRight(Amigo.java:455)
                                                                at me.ele.amigo.Amigo.work(Amigo.java:430)
                                                                at me.ele.demo.MainActivity.applyPatchApk(MainActivity.java:103)
                                                                at me.ele.demo.MainActivity$3.onClick(MainActivity.java:59)
                                                                at android.view.View.performClick(View.java:4438)
                                                                at android.view.View$PerformClick.run(View.java:18422)
                                                                at android.os.Handler.handleCallback(Handler.java:733)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at android.os.Looper.loop(Looper.java:136)

**Comment by JackCho** [comment]
yes, of course this doesn't work.
diff file is not an valid apk file, you need to use [bspatch](https://github.com/eleme/bspatch) to patch the installed apk & diff apk, then `demo.apk` comes out

**Comment by fldroid** [comment]
@JackCho Now everything is OK , thanks.
