### ISSUE TITLE
Activity 跳转的时候 ，intent附加Serializable对象报 java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by star0099** [eleme/Amigo#99]
09-28 19:27:45.752 26154-26154/me.ele.app.amigo E/Parcel: Class not found when unmarshalling: me.ele.demo.Bean
                                                          java.lang.ClassNotFoundException: me.ele.demo.Bean
                                                              at java.lang.Class.classForName(Native Method)
                                                              at java.lang.Class.forName(Class.java:309)
                                                              at java.lang.Class.forName(Class.java:273)
                                                              at android.os.Parcel.readParcelableCreator(Parcel.java:2281)
                                                              at android.os.Parcel.readParcelable(Parcel.java:2245)
                                                              at android.os.Parcel.readValue(Parcel.java:2152)
                                                              at android.os.Parcel.readArrayMapInternal(Parcel.java:2485)
                                                              at android.os.BaseBundle.unparcel(BaseBundle.java:221)
                                                              at android.os.Bundle.getParcelable(Bundle.java:755)
                                                              at android.content.Intent.getParcelableExtra(Intent.java:5254)
                                                              at me.ele.amigo.AmigoCallback.handleLaunchActivity(AmigoCallback.java:49)
                                                              at me.ele.amigo.AmigoCallback.handleMessage(AmigoCallback.java:38)
                                                              at android.os.Handler.dispatchMessage(Handler.java:98)
                                                              at android.os.Looper.loop(Looper.java:135)
                                                              at android.app.ActivityThread.main(ActivityThread.java:5294)
                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
                                                           Caused by: java.lang.ClassNotFoundException: Didn't find class "me.ele.demo.Bean" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]

**Comment by FtheGFW** [comment]
请问你的Bean实现了Serializable接口了吗？最后把你对关键代码片段贴一下

**Comment by star0099** [comment]
实现了Serialzable接口

Bean

public class Bean implements Serializable,Parcelable {

    private String name;

    private int id;

    public Bean() {
    }

    public Bean(String name, int id) {

        this.name = name;
        this.id = id;
    }

    @Override
    public String toString() {
        return "Bean{" +
                "name='" + name + '\'' +
                ", id=" + id +
                '}';
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(this.name);
        dest.writeInt(this.id);
    }

    protected Bean(Parcel in) {
        this.name = in.readString();
        this.id = in.readInt();
    }

    public static final Creator<Bean> CREATOR = new Creator<Bean>() {
        @Override
        public Bean createFromParcel(Parcel source) {
            return new Bean(source);
        }

        @Override
        public Bean[] newArray(int size) {
            return new Bean[size];
        }
    };
}

启动Activity
        Intent intent = new Intent(this, DemoActivity.class);
        intent.putExtra("Serializable", (Serializable) new Bean(this.getClass().getName(), 714));
        startActivity(intent);

取出Java Bean
        Intent intent = getIntent();
        if (intent.hasExtra("Serializable")) {
            Bean bean = (Bean) intent.getSerializableExtra("Serializable");
            Log.e(TAG, "TODO " + bean);
        } else {
            Log.e(TAG, "TODO no extra");
        }

**Comment by JackCho** [comment]
please try with `compile 'me.ele:amigo:0.3.1'` again

**Comment by star0099** [comment]
新版能正常工作了。

**Comment by JackCho** [comment]
Thanks for your feedback about Amigo @star0099
